version: 2.1
jobs:
  build:
    docker:
      # Primary container image where all steps run.
      - image: hashicorp/terraform:1.1.0
      # Secondary container image on common network.
      - image: google/cloud-sdk:slim

    working_directory: ~/

    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - run: echo $GCP_KEY
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - gcp-key