version: 2.1
jobs:
  log-in:
    docker:
      # Secondary container image on common network.
      - image: google/cloud-sdk:slim
    working_directory: ~/tf-jenkins-gke/dev
    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - checkout:
          path: ~/tf-jenkins-gke
      - run: echo $GCP_KEY > file.json
      - run: gcloud auth activate-service-account cd-jenkins@sandbox-io-289003.iam.gserviceaccount.com --key-file file.json --project=sandbox-io-289003
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    docker:
      # Secondary container image on common network.
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - attach_workspace:
          at: .
      - run: cat file.json
      - run: export GOOGLE_APPLICATION_CREDENTIALS=file.json
      - run: terraform init

workflows:
  new-workflow:
    jobs:
      - log-in:
          context:
            - gcp-key
      - build:
          requires:
            - log-in