version: 2.1
jobs:
  build:
    docker:
      # Primary container image where all steps run.
      - image: sennerholm/google-cloud-sdk-terraform:latest
      # Secondary container image on common network.
      - image: google/cloud-sdk:slim

    working_directory: ~/tf-jenkins-gke/dev

    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - checkout:
          path: ~/tf-jenkins-gke
      - run: gcloud auth activate-service-account cd-jenkins@sandbox-io-289003.iam.gserviceaccount.com --key-file $GCP_KEY --project=sandbox-io-289003
      - run: echo $GCP_KEY
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - gcp-key