version: '2.1'
orbs:
  terraform: circleci/terraform@3.0.0
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: /dev
      - terraform/validate:
          path: /dev
      - terraform/fmt:
          path: /dev
      - terraform/plan:
          path: /dev
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
